CREATE OR REPLACE FUNCTION trigger_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE OR REPLACE TRIGGER set_updated_at BEFORE
UPDATE ON movies FOR EACH ROW EXECUTE PROCEDURE trigger_updated_at();